using System;
using System.Windows.Forms;
using System.Windows.Forms.VisualStyles;
using System.Xml.Linq;
using System.Xml.XPath;
using ZbW.Testing.Dms.Client.ViewModels;
namespace ZbW.Testing.Dms.Client.Model
{
    public class Configuration
    {
        private string _repoLocationPath;
        private XDocument _configXml;
        private string _userName;
        public Configuration(string usr)
        {
            _userName = usr;
            ConfigXml = new XDocument();
            if (!ConfigXmlExists()) GenerateConfigFile();
        }

        public string RepoLocationPath
        {
            get => _repoLocationPath;
            set => _repoLocationPath = value;
        }

        public XDocument ConfigXml
        {
            get => _configXml;
            set => _configXml = value;
        }

        public string UserName => _userName;

        public bool DefineRepositoryPathDialog()
        {
            using ( var fld = new FolderBrowserDialog())
            {
                fld.ShowNewFolderButton = true;
                DialogResult result = fld.ShowDialog();

                if (result == DialogResult.OK && !string.IsNullOrWhiteSpace(fld.SelectedPath))
                {
                    _repoLocationPath = fld.SelectedPath;
                    string xpath = String.Format("//Config[@userID="+UserName+"]");
                    XElement ele = ConfigXml.XPathSelectElement(xpath);
                    if (ele.IsEmpty)
                    {
                        AddNewElement();
                    }
                    else
                    {
                        ele.Element("RepositoryPath").Value = RepoLocationPath;

                    }
                    return true;
                }
                return false;
            }
        }

        public void GenerateConfigFile()
        {
            if (ConfigXmlExists())
            {
                AddNewElement();
            }
            else
            {
                ConfigXml.Add(new XComment("Holds settings for each user || generated by DMS"));
                ConfigXml.Add(new XElement("DMS",
                        new XElement("Configs",
                            new XElement("Config", new XAttribute("configAddedAt", DateTime.Now), new XAttribute("userID", UserName),
                                new XElement("User", UserName),
                                new XElement("RepositoryPath", RepoLocationPath)
                            )
                        )
                    )
                );
            }
            
        }

        public bool ConfigXmlExists()
        {
            string appData = Environment.SpecialFolder.ApplicationData + "\\" + "ZbWDmsConfig.xml";
            return System.IO.File.Exists(appData);
        }

        public bool ConfigXmlUserKnown()
        {
            foreach (var element in ConfigXml.Elements())
            {
                XAttribute usr = element.Attribute("userId");
                if (usr.Value.Equals(UserName)) return true;
            }

            return false;
        }

        public void AddNewElement()
        {
            XElement configRecord;
            configRecord = new XElement("Config", new XAttribute("configAddedAt", DateTime.Now),
                new XElement("User", UserName),
                new XElement("RepositoryPath", RepoLocationPath)
            );
            foreach (var element in ConfigXml.Elements())
            {
                if (element.Name.Equals("Config"))
                {
                    element.AddAfterSelf(configRecord);
                }
            }
        }
    }
}